default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black

  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.0
  #   hooks:
  #     - id: bandit
  #       args: ["--ini=tox.ini"]

  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.9.2
  #   hooks:
  #     - id: flake8
  #       args: ["--config=tox.ini"]
  #       additional_dependencies: [flake8-isort]

  # - repo: https://github.com/timothycrosley/isort
  #   rev: 5.9.3
  #   hooks:
  #     - id: isort

  # - repo: https://github.com/pre-commit/pygrep-hooks
  #   rev: v1.9.0
  #   hooks:
  #     - id: rst-directive-colons
  #     # - id: rst-backticks
  #     - id: rst-inline-touching-normal
  #     - id: python-no-log-warn
  #     - id: python-no-eval
  #     - id: text-unicode-replacement-char
