# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  image: testing

sphinx:
  configuration: docs/conf.py

# How to install the project.  We need to specify to use `pip`, because
# otherwise RTD may try to directly execute `setup.py`, which doesn't exist.
python:
  version: 3.9
  install:
    - method: pip
      path: .
      requirements: docs/requirements.txt
      # extra_requirements:
      #   - docs
