version: 2

build:
  image: testing

sphinx:
  builder: html
  configuration: docs/conf.py
  # fail_on_warning: true

formats:
  - html

python:
  version: "3.9"
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
