name: Continous Deployment

on:
    push:
        branches:
            - main

    workflow_dispatch:

jobs:
    testing:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: actions/setup-python@v2

            - name: Install Poetry deps
              run: |
                  curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
                  export PATH=$PATH:$HOME/.poetry/bin
                  poetry install

            # - name: Run tox tests
            #   run: poetry run tox

            - name: Print current version
              run: poetry run semantic-release print-version --current

            - name: Print new version
              run: poetry run semantic-release print-version

            - name: Print poetry version
              run: poetry version --short

            - name: version
              run: echo "::set-output name=version::$(poetry run semantic-release print-version)"
              id: version

            - name: Create the release
              run: |
                  curl \
                  -X POST \
                  -H "Accept: application/vnd.github.v3+json" \
                  https://api.github.com/repos/imAsparky/sphinx-class-tocr/releases \
                  -d '{"tag_name":"$(version)"}'
