name: Continous Deployment

on:
    push:
        branches:
            - main

    workflow_dispatch:

jobs:
    testing:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              env: ${{secrets.CHANGELOG_UPDATE}}

              with:
                  fetch-depth: 0
            - uses: actions/setup-python@v2

            - name: Install Poetry deps
              run: |
                  curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
                  export PATH=$PATH:$HOME/.poetry/bin
                  poetry install

            # - name: Run tox tests
            #   run: poetry run tox

            - name: Print current version
              run: poetry run semantic-release print-version --current

            - name: Print new version
              run: poetry run semantic-release print-version

            - name: Print poetry version
              run: poetry version --short

            - name: version
              run: echo "::set-output name=version::$(poetry run semantic-release print-version)"
              id: version

            - name: release
              uses: actions/create-release@v1
              id: create_release
              with:
                  draft: false
                  prerelease: false
                  release_name: ${{ steps.version.outputs.version }}
                  tag_name: ${{ github.ref }}
                  body_path: CHANGELOG.md
              env:
                  GITHUB_TOKEN: ${{secrets.CHANGELOG_UPDATE}}
