name: Test and release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[testing]'

      - name: Test ${{ matrix.python-version }}
        run: |
          pytest tests --cov sphinxclasstocr

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.python-version }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

  # release:
  #   name: Release to PyPI
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/master'
  #   needs: [test]

  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         # Make sure the whole repository history is present, so that
  #         # python-semantic-release can decide if a new release is needed.
  #         fetch-depth: 0

  #     - uses: relekang/python-semantic-release@master
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         pypi_token: ${{ secrets.PYPI_TOKEN }}
