on:
    push:
        # branches: [main]

        tags:
            - dev-*

    workflow_dispatch:

jobs:
    publish_dev_build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: actions/setup-python@v2

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry tox tox-gh-actions semantic-release
            - name: test with tox
              run: poetry run tox

            - name: Check/update versions
              run: poetry run semantic-release version

            - name: Build dev
              run: |
                  poetry version $(poetry version --short)-dev.$GITHUB_RUN_NUMBER
                  poetry version --short
                  poetry build
            - name: publish to Test PyPI
              uses: pypa/gh-action-pypi-publish@master
              with:
                  user: __token__
                  password: ${{ secrets.TEST_PYPI_TOKEN}}
                  repository_url: https://test.pypi.org/legacy/
                  skip_existing: true

            - name: Release Drafter
              uses: release-drafter/release-drafter@v5
              with:
                  config-name: release-drafter.yaml
                  disable-autolabeler: true
              env:
                  GITHUB_TOKEN: ${{ secrets.TEST_PYPI_TOKEN}}
