# This is a basic workflow to help you get started with Actions

name: Test and Release PyPi Test

on:
    push:
        # branches: [main]

        tags:
            - dev-*

    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        concurrency: release

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Python Semantic Release
              uses: relekang/python-semantic-release@master
              with:
                  user: __token__
                  github_token: ${{ secrets.GITHUB_REPO_UPDATES }}
                  pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
# jobs:
#     publish_dev_build:
#         runs-on: ubuntu-latest

#         steps:
#             - uses: actions/checkout@v2
#             - uses: actions/setup-python@v2

#             - name: Install dependencies
#               run: |
#                   python -m pip install --upgrade pip
#                   pip install poetry tox tox-gh-actions
#             - name: test with tox
#               run: poetry run tox

#             - name: Check/update verions
#               run: poetry run semantic-release version

#             - name: Build dev
#               run: |
#                   poetry version $(poetry version --short)-dev.$GITHUB_RUN_NUMBER
#                   poetry version --short
#                   poetry build
#             - name: publish to Test PyPI
#               uses: pypa/gh-action-pypi-publish@master
#               with:
#                   user: __token__
#                   password: ${{ secrets.TEST_PYPI_TOKEN}}
#                   repository_url: https://test.pypi.org/legacy/
#                   skip_existing: true
