name: Auto-generate CHANGELOG-WIP
on:
    # release:
    #   types: [created, edited]
    # # schedule:
    #   - cron: "0 14 * * *"
    # push:
    #   branches:
    #     - main
    workflow_dispatch:

jobs:
    generate-changelog:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: BobAnkh/auto-generate-changelog@master
              with:
                  REPO_NAME: "imAsparky/sphinxclasstocr"
                  ACCESS_TOKEN: ${{secrets.CHANGELOG_UPDATE}}
                  PATH: "/CHANGELOG.md"
                  COMMIT_MESSAGE: "docs(CHANGELOG): update release notes:repo"
                  TYPE: "chore:Chore,feat:Feature,fix:Bug Fixes,docs:Documentation,perf:Performance Improvements,refactor:Refactor,style:Styling,test:Tests, WIP:In Progress"
